### ISSUE TITLE
[all szenarios] feedback and failureprotocol on task testing

### ISSUE THREAD

**Issue by denisehe** [strands-project/aaf_deployment#210] opened 2015-05-13 06:58 UTC
hey @marc-hanheide @cdondrup @Jailander @TobKoer following I will summarize things and issues that cam up during the testing yesterday:

Backend:
Nostop did not work, robot continued its patrole

Safety:
Henry drove against the walking stick of an elderly lady. as the bumper was released it started again, but the lady was still there - it was really a hairy situation - therfore: would it be possible to change the robots behavior there, so that after the bumper was hit and released it waits for some seconds until it starts moving again very slowely?

evasion in general is sometimes not sufficiant

Infoterminal:
screen scales need correction (navigation bar was visible on the lowerst section of screen)

Walking Group + Navigation in general:
the robot dirves a very zigg-zagging way - that is a bit irritating - as also the flashlights indicate a different direction every couple of meters. could waypoints be arranged in way that the ways are in total streighter?

Walking Group:
Robot loses navigation between Startingpoint and Rast1 - this does not occur when patrolling 
flashlights sometimes dont work

this "noooah" sound when the robot sounds firghtening ;-) i think another sound would be better

picture galery: therapists asked if it would be possible to show the pictures in an automatic galery, that would be helpful 

can be one more waiting-point be installed after Rast 2? 

yesterday it happened that music was played after switching music off (when starting the tour)

Bellbot:

Please adapt Voice output
Please adapt German rating quesitons

Speed: was a bit low in the beginning, but I am not sure as this was due to navigation problems or the general set up

GUI: Please could you insert a big headline on top of the gui that tells people that they need to enter the destination via the keyboard.

and can the robot also be sent to units resp. to the lifts going up to the units? 

GENERAL FEEDBACK

therapists found the walking group demo really cool! :-) and people over here are very curious about the robot :-)

**Comment by Jailander** [comment] 2015-05-13 07:56
Hi @denisehe :

Is this the safety stop issue or is it something different?

```
Backend:
Nostop did not work, robot continued its patrole
```

**Comment by marc-hanheide** [comment] 2015-05-13 08:23
## A few comments and questions:

Yes, @Jailander, I think it is. Did you fix it yet? 

---

@nilsbore can you have a look at this request for:

> Safety:
> Henry drove against the walking stick of an elderly lady. as the bumper was released it started again, but the lady was still there - it was really a hairy situation - therfore: would it be possible to change the robots behavior there, so that after the bumper was hit and released it waits for some seconds until it starts moving again very slowely?

So, could you see if we could a wait in the recovery behaviour, please? I think it does make sense.

@denisehe I can imagine it was a bit "hairy". While we certainly do our best to avoid such situations, it's not always entirely unavoidable. BTW, just the day I was at AAF I came out of a toilet and slammed the door (gently) against a resident. Accidents do happen also with us humans around... We must minimise risks by all means, which is why we object increasing the speed so much...

---

@denisehe on a side note: Could you log in to [gitter](https://gitter.im/strands-project/aaf_deployment) with your github account. We use that chat quite extensively and it's easiest to ask the quick and odd question.

---

> this "noooah" sound when the robot sounds firghtening ;-) i think another sound would be better

Again, @nilsbore, could you come up with something less scary? 

---

> and can the robot also be sent to units resp. to the lifts going up to the units?

It can (and @Jailander knows how to), but right now the robot would just go to the lift and not convey any further instructions, as those are not edited anywhere. So it's more work to to. Would it in that case not be easier and more transparent if the robot can take people to the lift, e.g. marked as "Lift zu den Stationen", in which case it would also be found when somebody types "Station"?

---

> the robot dirves a very zigg-zagging way - that is a bit irritating - as also the flashlights indicate a different direction every couple of meters. could waypoints be arranged in way that the ways are in total straighter?

As you might have noticed, we have been trying many things to find good waypoint, but we have a tricky optimisation problem, with partially contracting objectives. E.g. for the robot it would be best to have all waypoint in the middle of the corridor, away form any obstacles, but then it would be more disruptive to people in some place. Also, if we would disable human-aware navigation and make it more "stick to the path", then we would see fewer course corrections, but it would again be quite aggressive. 
But if it just zig-zags because some waypoints or edges are stupid, then that's for @Jailander to look at.

---

> GUI: Please could you insert a big headline on top of the gui that tells people that they need to enter the destination via the keyboard.

Really? There is only a keyboard on the whole screen, what else would people use? But sure, I can add more text...

**Comment by cdondrup** [comment] 2015-05-13 09:12
Indicators:

Indicating the correct direction, is not as easy as it might seem as we have to calculate it from the path the robot might take. Maybe @santosj can have a look if some parameters can be tuned.

---

> Robot loses navigation between Startingpoint and Rast1 - this does not occur when patrolling 
> flashlights sometimes dont work

I'll have a look at that today

---

> picture galery: therapists asked if it would be possible to show the pictures in an automatic galery, that would be helpful

Yes, will do.

---

> can be one more waiting-point be installed after Rast 2?

Easily done. Do you have a specific location in mind? Otherwise, I'll just pick one.

---

> yesterday it happened that music was played after switching music off (when starting the tour)

This is a general bug, will fix.

I'll open issues for some of these things, others will quickly be fixed.

**Comment by Jailander** [comment] 2015-05-13 09:22
https://github.com/strands-project/strands_navigation/pull/245 and https://github.com/strands-project/scitos_drivers/pull/109 Should do it, however there is still an issue with an action server not being preempted properly, all odds are in monitored navigation but I will do some testing to make sure.

> Yes, @Jailander, I think it is. Did you fix it yet? 

I only need to add the content for the stations, on the respective nodes but in the map @denisehe sent me there were different lifts for different stations eg

```
Lift1
2 OG, St. Edith
1 OG, St. Jakob

Lift2
3 OG, St. Hildegard
2 OG, St. Ladislaus
1 OG, St. Aaron
```

I can make the name of the content say for example Lift to St. Edith (auf deutch, naturlich) and it would take you to Lift1 is this fine? @denisehe @marc-hanheide 

> It can (and @Jailander knows how to), but right now the robot would just go to the lift and not convey any further instructions, as those are not edited anywhere. So it's more work to to. Would it in that case not be easier and more transparent if the robot can take people to the lift, e.g. marked as "Lift zu den Stationen", in which case it would also be found when somebody types "Station"?

**Comment by nilsbore** [comment] 2015-05-13 09:26
@denisehe Do you have any preference on what sound to play when the robot fails during a walking group? I suggest something like: https://www.youtube.com/watch?v=yJxCdh1Ps48 .

**Comment by cdondrup** [comment] 2015-05-13 09:31
#211 #212 #213 #214

**Comment by Jailander** [comment] 2015-05-13 09:32
I really don't know what to do about this one, I don't think any WayPoint is stupid now I have already added more and made bigger influence areas they are also very straight now, but as long as we need the waypoints in one side of the corridor this will keep happening I see no solution within the deployment time frame

> the robot dirves a very zigg-zagging way - that is a bit irritating - as also the flashlights indicate a different direction every couple of meters. could waypoints be arranged in way that the ways are in total straighter?

**Comment by cdondrup** [comment] 2015-05-13 09:33
Is there a way of reconfiguring the global planner to not try and go to the centre of the corridor between the waypoints?

**Comment by Jailander** [comment] 2015-05-13 09:35
no you can play with the inflation radius but that is minimal now, @bfalacerda has tested many different configurations and it doesn't help, as I have said many times the only 100% safe solution would be to use a non-movebase navigation on this edges

**Comment by nilsbore** [comment] 2015-05-13 09:40
@cdondrup I am implementing an RRT based planning approach for a course, this is something that would be nice to incorporate in this. Won't be ready for the deployments though.

**Comment by denisehe** [comment] 2015-05-13 09:41
@nilsbore - hi yes, that sound is cool :-)

**Comment by denisehe** [comment] 2015-05-13 09:43
@Jailander  I would make it that you can enter station XXX and that the robot brings you then to the lift and tells you what floor you have to go to

so that entering the station would be enough. because I think nobody would assume to enter "lift ..." (just to be on the safe side)

**Comment by Jailander** [comment] 2015-05-13 09:46
@nilsbore that sounds really good :+1: we definitely need more options on the local planner side, should definitely try that, however I don't think changing the whole navigation system during the deployment would have been a good idea anyway.

**Comment by Jailander** [comment] 2015-05-13 09:48
@denisehe as @marc-hanheide said there are no instructions implemented in the gui (I can definitely add them in the content), but if you search for station X it will appear lift to station X in the search bar, could that be intuitive enough?

> @Jailander I would make it that you can enter station XXX and that the robot brings you then to the lift and tells you what floor you have to go to

so that entering the station would be enough. because I think nobody would assume to enter "lift ..." (just to be on the safe side)

**Comment by denisehe** [comment] 2015-05-13 09:50
@Jailander yes as far as I can imagine it should be fine like that ;-)

**Comment by bfalacerda** [comment] 2015-05-13 09:52
what's the problem with the zig zagging? You have waypoints only on one side of the corridor, but when connecting them the robots makes an arc through the middle? is it a global or local planner issue?

**Comment by denisehe** [comment] 2015-05-13 09:53
@bfalacerda yes the robot plans from node to node but the nodes are sometimes not on a streight line, so the robot goes furhter to the middle reaches a node goes furhter to the side again - or that is a general navigation issue the robot shows although the points are on a line. I can not tell

**Comment by Jailander** [comment] 2015-05-13 09:56
no, now the nodes are on straight line

@bfalacerda  the problem is the arc between the waypoints, so yes local planner Issues

**Comment by Jailander** [comment] 2015-05-13 09:57
do you have any idea about this @bfalacerda?

**Comment by cdondrup** [comment] 2015-05-13 10:12
- global planner issue

**Comment by bfalacerda** [comment] 2015-05-13 10:44
so the global plan is already an arc? and the local planner happily follows? I guess it happens because the waypoints are really close to one side of the corridor?

The only way I know to control global plans now is via nogo maps, but that's a bad idea in  a corridor...

**Comment by Jailander** [comment] 2015-05-13 10:55
When I was testing I saw the local planner drifting away from the original plan not the local planner, but since I moved the waypoints closer to the walls I'll test again and find out, any ideas for the global planner

**Comment by bfalacerda** [comment] 2015-05-13 10:59
if its the local planner you might be able to get it to follow the global plan ,ore closely tweaking these http://wiki.ros.org/dwa_local_planner?distro=indigo#Trajectory_Scoring_Parameters

If its the global planner, no suggestions. I assume that it should do straight line plans, unless the waypoints are pretty close to one side of the corridor

**Comment by Jailander** [comment] 2015-05-13 11:00
Ok I'll try that thanks!!!!

**Comment by nilsbore** [comment] 2015-05-13 14:12
@marc-hanheide I have found a good sound for the walking group, how do I upload it to the media server? SSH?

**Comment by marc-hanheide** [comment] 2015-05-13 15:19
https://lcas.lincoln.ac.uk/henry/ usual login

**Comment by marc-hanheide** [comment] 2015-05-13 15:20
ah, wait... that won't work for file upload, right... Stick the file on dropbox and then wget on werner?

**Closed as completed** 2015-09-23 09:02 UTC
